package dev.maslov.sheetsync.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Stores a single set of API credentials per device.
 *
 * The [id] field is auto-generated by the database (typically will be 1).
 * The [clientId] is the user-input API client identifier.
 * The [clientSecret] is the user-input API client secret (encrypted at storage).
 *
 * Since this stores phone-level credentials (one set per device),
 * typically only one record exists in this table at a time.
 */
@Entity(tableName = "client_credentials")
data class ClientCredentials(
    /** Auto-generated by database, not user-set */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    /** User input: API client ID */
    val clientId: String = "",
    /** User input: API client secret */
    val clientSecret: String = ""
)
